"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  useInterview,
  useSubmitAnswer,
  useCompleteInterview,
} from "../api/use-interview";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Loader2, ChevronLeft, ChevronRight, Check } from "lucide-react";

interface InterviewSessionProps {
  interviewId: string;
}

export function InterviewSession({ interviewId }: InterviewSessionProps) {
  const router = useRouter();
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answers, setAnswers] = useState<Record<number, string>>({});

  const { data: interview, isLoading } = useInterview(interviewId);
  const submitAnswerMutation = useSubmitAnswer();
  const completeInterviewMutation = useCompleteInterview();

  if (isLoading || !interview) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  const questions = interview.questions;
  const currentQuestion = questions[currentIndex];
  const progress = ((currentIndex + 1) / questions.length) * 100;

  const handleAnswerChange = (value: string) => {
    setAnswers((prev) => ({ ...prev, [currentIndex]: value }));
  };

  const handleNext = () => {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex((prev) => prev + 1);
    }
  };

  const handlePrevious = () => {
    if (currentIndex > 0) {
      setCurrentIndex((prev) => prev - 1);
    }
  };

  const handleSubmit = async () => {
    // Submit all answers
    for (let i = 0; i < questions.length; i++) {
      const answer = answers[i];
      if (answer) {
        await submitAnswerMutation.mutateAsync({
          interviewId,
          questionIndex: i,
          answer,
          feedback: "", // Will be generated by AI
          score: 0, // Will be calculated by AI
        });
      }
    }

    // Complete the interview
    await completeInterviewMutation.mutateAsync(interviewId);

    // Navigate to results
    router.push(`/interviews/${interviewId}/result`);
  };

  const answeredCount = Object.keys(answers).filter(
    (key) => answers[Number(key)]?.trim()
  ).length;

  return (
    <div className="space-y-6">
      {/* Progress Header */}
      <div className="space-y-2">
        <div className="flex items-center justify-between text-sm text-muted-foreground">
          <span>
            Question {currentIndex + 1} of {questions.length}
          </span>
          <span>{answeredCount} answered</span>
        </div>
        <Progress value={progress} />
      </div>

      {/* Question Card */}
      <Card>
        <CardHeader>
          <div className="flex items-start justify-between gap-4">
            <CardTitle className="text-lg">
              {currentQuestion.question}
            </CardTitle>
            <Badge variant="outline">{currentQuestion.category}</Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label>Your Answer</Label>
            <Textarea
              placeholder="Type your answer here..."
              value={answers[currentIndex] || ""}
              onChange={(e) => handleAnswerChange(e.target.value)}
              rows={6}
            />
          </div>
        </CardContent>
      </Card>

      {/* Navigation */}
      <div className="flex items-center justify-between">
        <Button
          variant="outline"
          onClick={handlePrevious}
          disabled={currentIndex === 0}
        >
          <ChevronLeft className="mr-2 h-4 w-4" />
          Previous
        </Button>

        {currentIndex === questions.length - 1 ? (
          <Button
            onClick={handleSubmit}
            disabled={
              answeredCount === 0 ||
              submitAnswerMutation.isPending ||
              completeInterviewMutation.isPending
            }
          >
            {submitAnswerMutation.isPending ||
            completeInterviewMutation.isPending ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Submitting...
              </>
            ) : (
              <>
                <Check className="mr-2 h-4 w-4" />
                Complete Interview
              </>
            )}
          </Button>
        ) : (
          <Button onClick={handleNext}>
            Next
            <ChevronRight className="ml-2 h-4 w-4" />
          </Button>
        )}
      </div>
    </div>
  );
}
